services:
  - type: web
    name: ags-disiplin-botu
    runtime: node
    region: fra
    rootDir: bot
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
